### PR TITLE
New features

### PR DESCRIPTION
**Pull request by fabiocaccamo**
- Ordering field automatically replaced by a more user-friendly draggable icon
- Dragged row is a little bit transparent now
- Fixed body horizontal scroll when dragging rows outside browser viewport
- Fixed tabular inlines rows layout while sorting

All features has been tested against changelists, tabular-inlines and stacked-inlines.

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
Could you release a new version on pypi after merging?

**Comment by fabiocaccamo** [comment]
Generally ordering fields are used only by programmers, but backend users are not always programmers and they don't like ordering fields because they find them confusing. I discussed it recently with 3 different backend users, so I decided to replace the field with a draggable icon.

I perfectly understand, I think that a good solution would be provide apps settings like: `ADMIN_ORDERING_USE_ICON = True|False` and `ADMIN_ORDERING_SHOW_FIELD = True|False` then superusers will be affected by settings and staff users will see the only the icon.

I agree about making the row draggable using the icon only.

**Comment by matthiask** [comment]
Well, I have received mixed feedback about this.

I don't see the point in making the icon itself configurable -- the icon is certainly a plus. I also agree with adding `show_ordering_field_input = True` to `OrderableAdmin` and allowing people to override this in their modeladmin classes, but please don't hide the field by default.

**Comment by matthiask** [comment]
Re: Settings. I don't care much about the way you choose as long as inputs are shown by default. 

I'll also add a sentence or two to the README and the CHANGELOG if you do not want to do this in the PR.

**Comment by fabiocaccamo** [comment]
Ok, I like the idea to customize it in the model admin class.
Since the input will be visible by default, I think the custom options should be named `ordering_field_input_hidden = True`, do you agree?

**Comment by matthiask** [comment]
Yes, sounds better. Or maybe `ordering_field_hide_input = False` (sounds more direct to me), but your call!

**Comment by matthiask** [comment]
Thanks for the README.md, but there is already a README.rst. 

I hope you've seen the `tox.ini` file for running tests easily locally with tox (only with one combination of Python and Django, but that's on purpose)

**Comment by matthiask** [comment]
I'm merging the contents of both README files and fixing the tests now. Thanks for your work, it's awesome! Release coming soon.

**Comment by fabiocaccamo** [comment]
Thanks and sorry for the broken tests.

**Comment by matthiask** [comment]
Don't worry! It's not much work, certainly much less work than you put into this pull request. Thanks! :-)

**Comment by matthiask** [comment]
I just pushed 0.8 to PyPI.

**Comment by fabiocaccamo** [comment]
Thanks!

**Pull request merged**
